In [3]:
import numpy as np
def task_matrix():
    a = np.array([[5, 2, 0], [10, 4, 1], [7, 3, 2]])
    b = np.array([[3, 6, -1], [-1, -2, 0], [2, 1, 3]])
    c = (a**2 - b**2) * (a + b)
    print(c)

In [4]:
task_matrix()

[[ 128 -256    1]
 [ 891   24    1]
 [ 405   32  -25]]


In [5]:
def kramer():
    left = np.array([[1., 3., 5., 7.], [3., 5., 7., 1.], [5., 7., 1., 3.], [7., 1., 3., 5.]])
    right = np.array([12., 0., 4., 16.])
    print(np.linalg.solve(left, right))

In [6]:
kramer()

[ 1.00000000e+00 -1.00000000e+00 -1.01770444e-16  2.00000000e+00]


In [7]:
def task_3():
    n, m, r, c = map(int, input().split())
    x = np.full((n, m), 1)
    x[::r, :] = 0
    x[:, ::c] = 0
    print(x)


def task_5():
    n = int(input())
    x = np.full((n, n), 0)
    x[::2, :] = 1
    print(x)


def task_7():
    x = list(map(int, input().split()))
    z = np.array(x)
    for i in range(0, len(z)):
        if z[i] == 0:
            z[i] = -1
    print(z)


def task_9():
    n = int(input())
    x = np.arange(n, -1, -1)
    print(x)


def task_10():
    n, m = map(int, input().split())
    x = np.random.random((n, m))
    print(x)

    print(f"min: {np.min(x)}")

    print(f"max: {np.max(x)}")

    print(f"avg: {np.average(x)}")

    print(f"st_dev: {np.std(x)}")


def task_12():
    n = int(input())
    x = np.full((n, n), 0, dtype=float)
    x[1:n-1, 1:n-1] = 1
    print(x)


def task_14():
    x = np.array([0, 1])
    print(np.tile(x, [8, 4]))


def task_15():
    n = int(input())
    x = np.full((n, n), 1)
    x[:, ::2] = 0
    print(x)


def task_21():
    n, m = map(int, input().split())
    x = np.random.randint(0, m, (n, n))
    print(x)
    for i in range(0, n):
        for j in range(0, n):
            if x[i][j] == np.max(x):
                x[i][j] = np.max(x) * (-1)
    print(x)

In [8]:
task_3()

6 7 2 3
[[0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]]


In [9]:
task_5()

5
[[1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]]


In [10]:
task_7()

3 4 0 6 5 0 4 0
[ 3  4 -1  6  5 -1  4 -1]


In [11]:
task_9()

10
[10  9  8  7  6  5  4  3  2  1  0]


In [12]:
task_10()

4 5
[[0.40086236 0.73375794 0.95664811 0.86486541 0.27462145]
 [0.51584878 0.61024249 0.84198749 0.26535402 0.51723954]
 [0.95611978 0.02574818 0.07246569 0.88184805 0.3443562 ]
 [0.61900638 0.52124451 0.35064267 0.30718615 0.68611289]]
min: 0.025748180199608117
max: 0.9566481112298141
avg: 0.5373079039049816
st_dev: 0.2746192256011107


In [13]:
task_12()

4
[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


In [14]:
task_14()

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


In [15]:
task_15()

5
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]


In [16]:
task_21()

4 10
[[2 9 4 5]
 [7 5 6 2]
 [9 0 5 7]
 [7 0 3 0]]
[[ 2 -9  4  5]
 [ 7  5  6  2]
 [-9  0  5 -7]
 [-7  0  3  0]]
